[build]
  publish = "public"
  command = "hugo"

# URL: https://itsimplenow.com/
[context.production.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "prod_itsimplenow"

[context.production]
  command = "hugo --buildFuture && algolia/run-index-upload.sh -p"

# URL: https://dev--itsimplenow.netlify.app/
[context.dev.environment]
  HUGO_VERSION = "0.81.0"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "dev_itsimplenow"

[context.dev]
  command = "hugo --environment dev -b $DEPLOY_PRIME_URL --buildFuture --buildDrafts && algolia/run-index-upload.sh -p"

# Use this configuration for specific branch development
# URL: https://<feature-branch>--itsimplenow.netlify.app/
#[context.<feature-branch>.environment]
#  HUGO_VERSION = "0.72.0"
#  Algolia index name needed to run algolia/run-index-upload.sh
#  ALGOLIA_INDEX_NAME = "<feature-branch>_itsimplenow"
#
#[context.<feature-branch>]
#  command = "hugo --environment <feature-branch> -b $DEPLOY_PRIME_URL --buildFuture && algolia/run-index-upload.sh -p"
