[build]
  publish = "public"
  command = "hugo"

# URL: https://itsimplenow.com/
[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "prod_itsimplenow"

[context.production]
  command = "hugo --buildFuture && algolia/run-index-upload.sh -p"

# URL: https://dev--itsimplenow.netlify.app/
[context.dev.environment]
  HUGO_VERSION = "0.79.0"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "dev_itsimplenow"

[context.dev]
  command = "hugo --environment dev -b $DEPLOY_PRIME_URL --buildFuture --buildDrafts && algolia/run-index-upload.sh -p"
  command1 = "cat <<EOF loaderio-e00ca57f2d94c55c44a3e80a93ec16d3 >> loaderio-e00ca57f2d94c55c44a3e80a93ec16d3.txt EOF"

# Use this configuration for specific branch development
# URL: https://<feature-branch>--itsimplenow.netlify.app/
#[context.<feature-branch>.environment]
#  HUGO_VERSION = "0.72.0"
#  Algolia index name needed to run algolia/run-index-upload.sh
#  ALGOLIA_INDEX_NAME = "<feature-branch>_itsimplenow"
#
#[context.<feature-branch>]
#  command = "hugo --environment <feature-branch> -b $DEPLOY_PRIME_URL --buildFuture && algolia/run-index-upload.sh -p"
