# Enable / Disable Google Analytics statistics for your site
[languages]
    [languages.es]
        googleAnalytics = "UA-172585545-1"

# Enable / Disable comments on the articles via Disqus.
[params]
    [params.page]
        [params.page.comment]
            # Disqus comment config (https://disqus.com/)
            [params.page.comment.disqus]
                enable = false
                # Disqus shortname to use Disqus in posts
                shortname = "itsimplenow"
