[params]
    # Enable / Disable Google Analytics statistics for your site
    [params.analytics]
        enable = true
        # Google Analytics
        [params.analytics.google]
            id = "UA-172585545-1"
            # whether to anonymize IP
            anonymizeIP = true
    # Enable / Disable comments on the articles via Disqus.
    [params.page]
        [params.page.comment]
            enable = true
            # Disqus comment config (https://disqus.com/)
            [params.page.comment.disqus]
                enable = true
                # Disqus shortname to use Disqus in posts
                shortname = "itsimplenow"
